/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hbs.acceso;

import com.digitalpersona.uareu.UareUException;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Pacheco
 */
public class FormHuellas extends javax.swing.JFrame implements Lector.EnrolamientoListener{

    
    Lector l;
    byte[] huella;
    
    /**
     * Creates new form FormHuellas
     */
    public FormHuellas() {
        try {
            initComponents();
            setLocationRelativeTo(null);
            l = new Lector();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error al conectar con lector de huellas");
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        btn_huella = new javax.swing.JButton();
        lbl_huella = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ID Empleado");

        btn_huella.setText("Detectar huella");
        btn_huella.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_huellaActionPerformed(evt);
            }
        });

        lbl_huella.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbl_huella.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_id))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbl_huella, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_huella))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_huella)
                    .addComponent(lbl_huella))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    int capturas = 0;
    
    private void btn_huellaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_huellaActionPerformed
        capturas = 0;
        l.enrolar(this);
        btn_huella.setEnabled(false);
    }//GEN-LAST:event_btn_huellaActionPerformed

    
    @Override
    public void eventoEnrolamiento(Lector.Evento e, String msg) {
        if(e == Lector.Evento.DETECTAR){
            lbl_huella.setText("Capturas restantes: "+(4-capturas++));
        }
        else if(e == Lector.Evento.FINALIZADO){
            try {
                lbl_huella.setText("Huella capturada");
                btn_huella.setEnabled(true);
                PreparedStatement ps = DB.getConexion().prepareStatement("update empleado set fingerprint = ? where idEmpleado="+Integer.parseInt(txt_id.getText()));
                huella = l.getData();
                ps.setBytes(1, huella);
                
                int id = ps.executeUpdate();
                JOptionPane.showMessageDialog(null, "Huella registrada correctamente");
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Error al registrar huella");
                ex.printStackTrace();
            }
            
        }
        else{
            lbl_huella.setText("Error: "+msg);
            btn_huella.setEnabled(true);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormHuellas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormHuellas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormHuellas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormHuellas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormHuellas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_huella;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_huella;
    private javax.swing.JTextField txt_id;
    // End of variables declaration//GEN-END:variables
}
